CREATE TABLE "UPI_META_BANK_ACCOUNT" (
   	"ID" VARCHAR2(36) NOT NULL,
    "MOBILE_NO" VARCHAR2(100 BYTE),
	"ACC_NAME" VARCHAR2(100 BYTE),
	"ACC_IFSC" VARCHAR2(100 BYTE),
	"ACC_TYPE" VARCHAR2(100 BYTE),
	"ACC_NUM" VARCHAR2(100 BYTE),
	"BANK_NAME" VARCHAR2(100 BYTE),
	"BANK_CODE" VARCHAR2(100 BYTE),
	"BANK_BRANCH" VARCHAR2(100 BYTE),
	"DEBIT_CARD_NO" VARCHAR2(100 BYTE),
	"DEBIT_CARD_EXPIRY" VARCHAR2(100 BYTE),
	"DEBIT_CARD_PIN" VARCHAR2(100 BYTE),
	"NET_AMOUNT" NUMBER,
	"DATETIME_CREATED" TIMESTAMP (3),
	CONSTRAINT "PK_UPI_META_BANK_ACCOUNT" PRIMARY KEY ("ID")
);

CREATE INDEX "UPI_META_BANK_ACCOUNT_INDEX1" ON "UPI_META_BANK_ACCOUNT" ("ACC_NUM"); 